apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    name: sample-smile-app
  name: sample-smile-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: sample-smile-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 33%
      maxSurge: 33%
  template:
    metadata:
      labels:
        name: sample-smile-app
    spec:
      containers:
        - env:
          image: miladbeigi/sample-smile-app:0.0.5
          name: sample-smile-app
          ports:
            - containerPort: 3001
          livenessProbe:
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
      restartPolicy: Always
