name: Security
on:
  push:
    branches:
      - main

jobs:
  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get the version
        run: |
            VERSION=$(cat app/VERSION | tr -d '\n') 
            echo VERSION=$VERSION >> $GITHUB_ENV

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
            image: miladbeigi/sample-smile-app:$VERSION
            args: --severity-threshold=critical