name: Test
on:
    push:
        branches:
            - main

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        working-directory: app
        run: |
          make build
