name: Test
on:
    push:
        branches:
            - main

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        working-directory: app
        run: |
          make build

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.4

      - name: Initialize Terraform
        id: init
        working-directory: infra
        run: |
          terraform init

      - name: format
        working-directory: infra
        run: |
          terraform fmt -check -diff -recursive .

      - name: Validate Terraform
        id: validate
        working-directory: infra
        run: |
          terraform validate